import type { Metadata } from "next";
import localFont from "next/font/local";

import HCStack from "@/components/base/stack/HCStack";

import AppRegister from "../AppRegister";
import "./globals.css";

/** Pretendard 폰트 적용 */
const pretendard = localFont({
  src: "../../public/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${pretendard.variable} font-pretendard font-semibold`}>
      <body className={pretendard.className}>
        <AppRegister>
          <HCStack className="w-screen justify-center">
            <HCStack className="h-screen w-full min-w-[375px] max-w-[430px]">{children}</HCStack>
          </HCStack>
        </AppRegister>
      </body>
    </html>
  );
}
