import type { Metadata } from "next";
import localFont from "next/font/local";
import Image from "next/image";

import { useEffect } from "react";

import AppLayout from "@/components/AppLayout";
import HCStack from "@/components/base/stack/HCStack";
import VCStack from "@/components/base/stack/VCStack";

import AppRegister from "../AppRegister";
import "./globals.css";

/** Pretendard 폰트 적용 */
const pretendard = localFont({
  src: "../../public/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${pretendard.variable} font-pretendard font-semibold`}>
      <body className={pretendard.className}>
        <AppRegister>
          <AppLayout>{children}</AppLayout>
        </AppRegister>
      </body>
    </html>
  );
}
